// Generated by CoffeeScript 1.6.2
(function() {
  var addLink, data, hoverOverLink, inputDispatch, insertListItem, matchBack, matchForward;

  data = ["charlie Parker", "john Coltrane", "miles Davis", "joe Pass", "max Roach", "dizzie Gillespie", "bud Powell", "charles Mingus", "sonny Rollins", "django Reindhardt", "duke ellington", "albert ayler", "louis armstrong", "billie holiday"];

  $("input").on("keydown", function(e) {
    return setTimeout(inputDispatch, 150, e);
  });

  insertListItem = function(a) {
    return "<a><li style='list-style-type:none'>" + a + "</li></a>";
  };

  matchForward = function(input) {
    var key, _results;

    _results = [];
    for (key in data) {
      if (input === data[key].charAt(input.length - 1)) {
        $("li").addClass("li:first-letter");
        _results.push(insertListItem(data[key]));
      } else if (input === data[key].substr(0, 2)) {
        _results.push(insertListItem(data[key]));
      } else if (input === data[key].substr(0, 3) || input === data[key].substr(0, 4) || input === data[key].substr(0, 5) || input === data[key].substr(0, 6)) {
        _results.push(insertListItem(data[key]));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  matchBack = function() {
    var key, _results;

    _results = [];
    for (key in data) {
      if ($("input").val() === data[key].substr(0, 6)) {
        _results.push(insertListItem(data[key]));
      } else if ($("input").val() === data[key].substr(0, 5)) {
        _results.push(insertListItem(data[key]));
      } else if ($("input").val() === data[key].substr(0, 4)) {
        _results.push(insertListItem(data[key]));
      } else if ($("input").val() === data[key].substr(0, 3)) {
        _results.push(insertListItem(data[key]));
      } else if ($("input").val() === data[key].substr(0, 2)) {
        _results.push(insertListItem(data[key]));
      } else if ($("input").val() === data[key].substr(0, 1)) {
        _results.push(insertListItem(data[key]));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  addLink = function() {
    return $("ul").find("li").on("click", function(e) {
      var href;

      href = $(this).text();
      return $(this).parent().attr("href", "http://en.wikipedia.org/wiki/" + href);
    });
  };

  hoverOverLink = function() {
    return $("ul").find("a").hover(function() {
      return $(this).addClass("hover");
    }, function() {
      return $(this).removeClass("hover");
    });
  };

  inputDispatch = function(e) {
    e.preventDefault();
    if (e.keyCode !== 8) {
      $("ul").html(matchForward(e.target.value, e)).addClass("match");
      hoverOverLink();
      return addLink();
    } else if (e.keyCode === 8) {
      $("ul").html(matchBack());
      hoverOverLink();
      addLink();
      if ($("input").val().length <= 0) {
        return $("ul").removeClass("match");
      }
    }
  };

}).call(this);
